---
apiVersion: v1
kind: Service
metadata:
  name: agent-svc
  namespace: demo
spec:
  selector:
    app.kubernetes.io/name: agent
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: agent
    spec:
      containers:
        - name: agent
          image: pkbhowmick/agent:v0.0.1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env:
            - name: SDK_KEY
              valueFrom:
                secretKeyRef:
                  name: agent-secret
                  key: sdkKey
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: agent-secret
                  key: natsURL
